name: ignite3

services:
  node1:
    image: apacheignite/ignite:3.1.0
    command: --node-name node1
    environment:
      JVM_MAX_MEM: "2g"
      JVM_MIN_MEM: "2g"
    ports:
      - "10300:10300"   # REST API port
      - "10800:10800"   # Thin Client port